apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sphela-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: sphela-app
        app: sphela
    spec:
      imagePullSecrets:
      - name: docker-registry-secret
      containers:
      - name: sphela-app
        image: gcr.io/sphela-153202/sphela-app:v10
        ports:
        - containerPort: 9100
        volumeMounts:
            - name: src
              mountPath: /www/sphela/app/src/
      volumes:
        - name: src
          persistentVolumeClaim:
            claimName: srclaim
