---
apiVersion: v1
kind: Service
metadata:
  name: lb
spec:
  ports:
    - port: 80
      name: http
      targetPort: 80
    - port: 443
      name: https
      targetPort: 443
  selector:
    run: sphela-nginx
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sphela-nginx
spec:
  replicas: 2
  template:
    metadata:
      labels:
        run: sphela-nginx
        app: sphela
    spec:
      imagePullSecrets:
      - name: docker-registry-secret
      volumes:
      - name: letsencrypt-volume
        secret:
          secretName: letsencrypt
      - name: dhparam-volume
        secret:
          secretName: dhparam
      containers:
      - name: sphela-nginx
        image: gcr.io/sphela-153202/sphela-nginx:v38
        ports:
        - containerPort: 80
        volumeMounts:
        - name: letsencrypt-volume
          readOnly: true
          mountPath: "/etc/letsencrypt/live/certs"
        - name: dhparam-volume
          readOnly: true
          mountPath: "/etc/letsencrypt/live/dhparam"
